### ISSUE TITLE
Linting in CI

### ISSUE THREAD

**Issue by rwjblue** [tildeio/glimmer#137]
We need to ensure that new PR's do not introduce type issues, I see the path for this something like the following:

- [x] Add `npm run vscode-build` to `.travis.yml`'s `script` (this will get at least a pass/fail for PR's until better testing can get setup).
- [ ] Incorporate [broccoli-tslinter](https://github.com/kratiahuja/broccoli-tslinter) to enable live reload style testing.

**Comment by GavinJoyce** [comment]
This can be closed (I forgot to add `closes #xyz` to the [PR](https://github.com/tildeio/glimmer/pull/214))
