### ISSUE TITLE
Benchmarks Cleanup

### ISSUE THREAD

**Issue by chancancode** [tildeio/glimmer#159]
#158 is the wrong fix. We introduced the problem around #149. The problem is in `glimmer-demos/index.ts`, we re-export stuff from the bench* files. This is problematic because we try to access the `Benchmark` global variable [here](https://github.com/tildeio/glimmer/blob/master/packages/glimmer-demos/lib/bench.ts#L10) as soon as you require that file. You need to load the `benchmark.js` on the page for that global to be available, which is why adding the script tag to everything fixes it.

However, since all the demos don't otherwise use `Benchmark` library, adding the script tag to everything is a bit silly. Instead, we should move all the benchmark stuff in to a new, top-level `glimmer-benchmarks` package and make the page available in `https://localhost:4200/benchmarks.html` or something. We already did the work to make it a single HTML page – we can include `benchmark.js` in that page but we won't have to do it in the other demos. Since demos have no reason to require the benchmark stuff, it won't have need to access the `Benchmark` global anymore.

**Comment by locks** [comment]
I can look into it since I was already poking around before I took the easy way out with #158. With the above instructions, the proper fix is clearer.
