### ISSUE TITLE
Handlebars 4.x support?

### ISSUE THREAD

**Issue by rafde** [tildeio/glimmer#224]
Glimmer has handlebars ^3.0.1 support but some of the niceness of decorators and block partials are missing.

I changed the package version to ^4.0.0 so my fork would let me use Handlebars 4 but threw an error when I tried using

```
{{#*inline "myPartial"}}
  My Content
{{/inline}}
```

where the error was

> parser.ts:52 Uncaught TypeError: this[node.type] is not a function

Is there a possible future for using ^4.0.0 (and 5.0.0 someday)?

**Comment by Turbo87** [comment]
@mmun @rwjblue what's the tl;dr here? do we want to stay on old handlebars? do we want to update? it seems that AST fixes in handlebars can only be unlocked if we update to 4.x at some point. would it be possible to update to 4.x but without supporting certain new constructs like the above?

**Comment by rwjblue** [comment]
> do we want to stay on old handlebars?

No.

> do we want to update?

Yes.

> it seems that AST fixes in handlebars can only be unlocked if we update to 4.x at some point. 

Confirm, we need to update.

> would it be possible to update to 4.x but without supporting certain new constructs like the above?

Yes.  One way would be by detecting them via an AST walker and throwing a compilation error.

**Comment by rafde** [comment]
> would it be possible to update to 4.x but without supporting certain new constructs like the above?

What would be turned off?
- Decorators and Inline Partials
- partial blocks
- partials
- block parameters

**Comment by mmun** [comment]
@rafde Partials (specifically the `{{> foo}}` syntax and its variations and decorators. They weren't designed with glimmer in mind and it's not clear at this time how they fit into our component story.

**Comment by rafde** [comment]
hmm... can `{{> foo}}` get evaluated to [`{{partial "foo"}}`](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_partial) or a component?

I was hoping to use glimmerjs to replace handlebarsjs to reap the benefits but the templates I've been creating use inline decorators and partials a lot.

**Comment by Turbo87** [comment]
@rafde partials are now deprecated in Ember too. If you want to use partials then you should probably continue using handlebars.

**Comment by chadhietala** [comment]
Partials are not deprecated. They require an RFC and some work to be done in Glimmer to be deprecated.

**Comment by rwjblue** [comment]
Confirm. However, we do not support the Handlebars special syntax for partials (which is what we will disable in #397 before landing the Handlebars update).

**Comment by Turbo87** [comment]
@chadhietala sorry, thought I read about that deprecations somewhere, but apparently I confused it with something else

**Comment by chadhietala** [comment]
This has now  landed in #397

**Comment by rafde** [comment]
@Turbo87 [{{render}}](http://emberjs.com/deprecations/v2.x/#toc_code-render-code-helper) is getting deprecated.

Any advice regarding having glimmerjs work with existing Handlebarsjs project? 
I've wanted to use this for a while without having to switch out the framework that is used at work to emberjs.

I figure glimmerjs is the best shot of getting handlebars syntax with (better than?) react performance. So for I noticed that the substitute for partials is using a glimmer class to render the string which is then given to another glimmer object to use via `<...>` and gets registered somehow to glimmerjs.
