### ISSUE TITLE
Implement caching in TestEnvironment

### ISSUE THREAD

**Issue by chadhietala** [tildeio/glimmer#228]
Now that caching for layouts is done by consuming env we should implement this caching in the `TestEnvironment` so our benches and demos don't artificially regress.

**Comment by chancancode** [comment]
oops. can probably just cache it in a Dict in the TestEnvironment. For our purpose, using the component name as cache key is probably enough. Alternatively, we could even re-implement caching it on the test environment's component definition objects.
