### ISSUE TITLE
Determine NPM Package Name

### ISSUE THREAD

**Issue by rwjblue** [tildeio/glimmer#23]
Looks like `glimmer` is already used on NPM: https://www.npmjs.com/package/glimmer

---

What should we use when publishing this?

**Comment by runspired** [comment]
Glamorous

**Comment by rwjblue** [comment]
I personally would prefer to keep a [Destiny](https://www.bungie.net/en/pub/AboutDestiny) flavored name (Glimmer is the in-game currency in Destiny)... :smile_cat:

**Comment by chadhietala** [comment]
Señor @tomdale is squatting on https://www.npmjs.com/package/glimmer-engine.

**Comment by rwjblue** [comment]
> Señor @tomdale is squatting on https://www.npmjs.com/package/glimmer-engine.

Darn.  I was going to make a pitch for `sunbreaker`...

@tomdale - Can you `npm owner add rwjblue glimmer-engine`?

**Comment by tomdale** [comment]
@rwjblue Done
