### ISSUE TITLE
Fix TSLint Issues

### ISSUE THREAD

**Issue by rwjblue** [tildeio/glimmer#243]
When https://github.com/tildeio/glimmer/pull/242 updated the `tests/index.html` to require the `.tslint` files, a number of modules were indicated as failing.

We need to uncomment [this line](https://github.com/tildeio/glimmer/blob/b7f441fd65a84f85933646c171e7d816af24451d/ember-cli-build.js#L176) and fix any linting errors that show up.

**Comment by chancancode** [comment]
cc @GavinJoyce

**Comment by GavinJoyce** [comment]
I've just started to look into this.

[`tsLintTree`](https://github.com/tildeio/glimmer/blob/932571c9ebfbf4526718e90e6c4facd2cadf652c/ember-cli-build.js#L80-L82) seems incorrect, here is the contents of `glimmer-benchmarks/index.tslint.ts` in that tree:

```js
QUnit.module('JSHint - glimmer-benchmarks');
QUnit.test('glimmer-benchmarks/index.ts should pass jshint', function(assert) {
  assert.expect(1);
  assert.ok(false, 'glimmer-benchmarks/index.ts should pass jshint.\n\n');
});
```

Things to find out:

 [ ] why is the asserton `jshint` and not `tslint`?

**Comment by GavinJoyce** [comment]
There are bugs in `broccoli-tslinter` which I'll fix this evening
