### ISSUE TITLE
Convert glimmer-syntax Parser to `class`

### ISSUE THREAD

**Issue by locks** [tildeio/glimmer#368]
The glimmer-syntax's `Parser` class is currently using a function constructor instead of the `class` keyword.
This should be a mostly mechanical translation, being the `for` loops used for property definitions possibly the trickier bit.

Relevant code: https://github.com/tildeio/glimmer/blob/master/packages/glimmer-syntax/lib/parser.ts#L41-L101
Example of a `class`: https://github.com/tildeio/glimmer/blob/fe539562bbaf3229352214a2da645c0269c39e0f/packages/glimmer-util/lib/logger.ts#L24-L61

You can reach me or @Turbo87 for help!

**Comment by robbiepitts** [comment]
I'll take a stab tonight.

**Comment by Turbo87** [comment]
@rwjblue @mmun I think this can be closed now
