### ISSUE TITLE
TextNode in ConcatStatement has no loc=null

### ISSUE THREAD

**Issue by Turbo87** [tildeio/glimmer#399]
Example:

```hbs
<h1 class="{{if active "active" "inactive"}} foo">Test</h1>
```

The "foo" `TextNode` has `loc: null`.

/cc @mmun

**Comment by rwjblue** [comment]
As far as I can see, there is no "foo" in the provided snippet...

**Comment by Turbo87** [comment]
@rwjblue it's behind the curly inside of the `class` attribute

**Comment by Turbo87** [comment]
Example in AST Explorer: https://astexplorer.net/#/rMac18pOSk

**Comment by rwjblue** [comment]
Derp. Sorry.

**Comment by rwjblue** [comment]
Submitted https://github.com/tildeio/glimmer/pull/401 to fix.
