### ISSUE TITLE
Adding transform property to inline SVG errors in TreeConstruction class

### ISSUE THREAD

**Issue by myasonik** [tildeio/glimmer#405]
Adding an inline transform property to an SVG throws an error: `Error: <g> attribute transform: Expected '(', "translateY(-8px)".`

MDN page on transform property for SVG elements: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

Ember Twiddle test case (error in console, no visual output): https://ember-twiddle.com/8f77549f8e114729fb5c82eb62a2feff?openFiles=templates.application.hbs%2C

**Comment by chadhietala** [comment]
I don't think this is a Glimmer issue as that HTML creates a parse error in Chrome outside of Glimmer. https://jsfiddle.net/16kwedms/

**Comment by myasonik** [comment]
In case anyone else stumbles into this, it looks like browsers don't like pixel values in inline transform properties and only like transform properties are certain SVG tags.

MDN docs weren't very clear on either point.
