### ISSUE TITLE
Question about opcodes

### ISSUE THREAD

**Issue by tomasznapieralski** [tildeio/glimmer#409]
Hello,

Before i will ask question i would like to say that you have done awesome work in Glimmer project and i cannot wait to see what will you do next :)

Could you point me to code which is responsible render/re-render templates from opcodes and explain more how does it work?

If i compare Ember component from Glimmer 1 output and from Glimmer 2 output, i can see that in Glimmer 1 output there are many javascript instructions that are operating on DOM, like createElement, append and so on, while in Glimmer 2 output there are not, instead there are opcodes.

**Comment by GavinJoyce** [comment]
Hey @tomasznapieralski, have you seen the following two videos? They both go into details about opcodes and the VMs:

 * https://www.youtube.com/watch?v=DrFXw0QGDLM (this was recorded in 2015 and compares Glimmer 1 and what would become Glimmer 2)
 * https://www.youtube.com/watch?v=vL8sCi1Bv6E (this was recorded last year as Glimmer 2 was almost complete)

**Comment by locks** [comment]
Closing the issue as Gavin provided resources to dive deeper. You can carry out the exploration in the #dev-glimmer channel of the Ember slack!

**Comment by tomasznapieralski** [comment]
Thank you @GavinJoyce, these videos answers my questions, especially your talk :)
If i will have more questions i will ask on Slack.
