### ISSUE TITLE
Lazy component compilations

### ISSUE THREAD

**Issue by chancancode** [tildeio/glimmer#44]
Currently, `TestEnvironment#registerComponent` eagerly compiles the component layout, which causes it to try to lookup other component definitions that might not have been loaded yet (which then causes the compiler to emit `OpenPrimitiveElement`).

(This is just a `TestEnvironment` implementation issue, so it shouldn't require any Glimmer changes)

**Comment by chadhietala** [comment]
Working on this one.

**Comment by chadhietala** [comment]
Closed by #50
