### ISSUE TITLE
`loc` info for `TextNode`s and `CommentNode`s is not populated

### ISSUE THREAD

**Issue by rwjblue** [tildeio/glimmer#89]
This is also an issue in HTMLBars, but I wanted to record the issue here (as it is unlikely that we would make many changes in tildeio/htmlbars).

Both `TextNode` and `CommentNode` are built without `loc`, and `loc` is not populated during `finishComment` or `finishData`.

Some links:

* `b.text` without `loc` -- https://github.com/tildeio/glimmer/blob/master/packages/node_modules/glimmer-syntax/lib/parser/tokenizer-event-handlers.ts#L27
* `b.comment` without `loc`-- https://github.com/tildeio/glimmer/blob/master/packages/node_modules/glimmer-syntax/lib/parser/tokenizer-event-handlers.ts#L13
* `buildComment` doesn't accept a `loc` param -- https://github.com/tildeio/glimmer/blob/master/packages/node_modules/glimmer-syntax/lib/builders.ts#L46-L51

**Comment by HeroicEric** [comment]
This was covered by https://github.com/tildeio/glimmer/pull/135, right?

**Comment by rwjblue** [comment]
Yes, thank you!
